# -----------------------------------------------------------------------------
# Project Configuration File
# -----------------------------------------------------------------------------
# This file contains the configuration settings for the ECB multi-country B2B
# analysis.
# Modify the parameters below as needed to adjust the behavior of the 
# application. The configuration settings define parameters to generate random 
# data or use real data for analysis. It also specifies input files used in 
# the analysis, along with their respective file types (e.g., CSV, Stata).
# 
# Instructions:
# 1. Set the `start_year` and `end_year` to define the range of years for the 
#    data generation process. You can also change the number of firms and number
#    of connections between firms you want the program to generate. Default is
#    1.000 and 10.000 respectively.
# 2. The `data_type` variable can be set to either "real" or "random", 
#    depending on the type of data you want to analyze.
# 3. Specify both the name and the type of the input files in the `input_files` 
#    section. Supported file types include "csv" for CSV files and "stata" for 
#    Stata (.dta) files.
#
# -----------------------------------------------------------------------------
# Author: Alberto Palazzolo
# Last Modified: September 2024
# -----------------------------------------------------------------------------
# Settings for Data Generation
data_generation:
  nfirms: 1000        # Number of firms
  nlinks: 10000      # Number of links between firms

# Years
years:
  start_year: 2018    # The first year to generate or analyze data
  end_year: 2018      # The last year to generate or analyze data

# Choose the type of data to use:
# "real" - Use real data from input files
# "random" - Generate random data for analysis
data_type: "random"

# Input Files for Analysis
# Define the name and the type of each input file
# 1. B2B Data
b2b_data:
  file_name: "B2B_data_pseudonymized"
  extension: "dta"    # Specify file type: "csv" or "dta" (if Stata file)

# 2. Firm-Level Data
firm_data:
  file_name: "firm_data_final"
  extension: "dta"  # Specify file type: "csv" or "dta" (if Stata file)